package com.sigrap.category;

import java.time.LocalDateTime;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Response object containing category information.
 * Used for returning category data in API responses.
 *
 * <p>This class:
 * <ul>
 *   <li>Represents category read operations</li>
 *   <li>Includes audit information</li>
 *   <li>Contains complete category details</li>
 * </ul></p>
 *
 * <p>Key Features:
 * <ul>
 *   <li>Immutable category data</li>
 *   <li>Timestamp tracking</li>
 *   <li>Complete category representation</li>
 * </ul></p>
 *
 * <p>Usage Example:
 * <pre>
 * CategoryInfo info = CategoryInfo.builder()
 *     .id(1)
 *     .name("Office Supplies")
 *     .description("General office supplies and stationery")
 *     .createdAt(LocalDateTime.now())
 *     .updatedAt(LocalDateTime.now())
 *     .build();
 * </pre></p>
 *
 * @see CategoryController
 * @see CategoryService
 * @see CategoryMapper
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Response object containing category information")
public class CategoryInfo {

  /**
   * The unique identifier of the category.
   *
   * <p>Properties:
   * <ul>
   *   <li>Auto-generated by the database</li>
   *   <li>Immutable after creation</li>
   *   <li>Used as primary key</li>
   * </ul></p>
   */
  @Schema(description = "Unique identifier of the category", example = "1")
  private Integer id;

  /**
   * The name of the category.
   *
   * <p>Properties:
   * <ul>
   *   <li>Unique across all categories</li>
   *   <li>Used for display and organization</li>
   *   <li>Main identifier for users</li>
   * </ul></p>
   */
  @Schema(description = "Name of the category", example = "Office Supplies")
  private String name;

  /**
   * The description of the category.
   *
   * <p>Properties:
   * <ul>
   *   <li>Optional detailed information</li>
   *   <li>Provides additional context</li>
   *   <li>Used for documentation</li>
   * </ul></p>
   */
  @Schema(
    description = "Description of the category",
    example = "Items used in office environments"
  )
  private String description;

  /**
   * The timestamp when the category was created.
   *
   * <p>Properties:
   * <ul>
   *   <li>Automatically set on creation</li>
   *   <li>Immutable after creation</li>
   *   <li>Used for auditing</li>
   * </ul></p>
   */
  @Schema(
    description = "Date and time when the category was created",
    example = "2023-01-15T10:30:00"
  )
  private LocalDateTime createdAt;

  /**
   * The timestamp when the category was last updated.
   *
   * <p>Properties:
   * <ul>
   *   <li>Automatically updated on changes</li>
   *   <li>Used for tracking modifications</li>
   *   <li>Helps with versioning</li>
   * </ul></p>
   */
  @Schema(
    description = "Date and time when the category was last updated",
    example = "2023-01-20T14:45:00"
  )
  private LocalDateTime updatedAt;
}
